// <auto-generated />
namespace QuanLyKhachSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcolumnstar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolumnstar));
        
        string IMigrationMetadata.Id
        {
            get { return "202305020243092_add-column-star"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
